apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  # Replace 'your-openai-api-key-here' with your actual base64 encoded OpenAI API key
  # To encode: echo -n 'sk-your-actual-api-key' | base64
  api-key: c2stcHJvai0zeFB0Q21FSnFoNDNCVjJIQWZkRDYxUmljcVRzNUx2OTY0M1g1bVoxTDFtNHhNVXAxdTFxYlVVeXQzMTVEcGlmWlRmTC15c3BzT1QzQmxia0ZKQnZMc3poczViTktWNjZqQWdlTjdVZVNzNmEya1VvcjNIdFhQUTMwNnRxMHd4MTVJOE9lQlBCWFZTZ0JOa0JfOVJOUnlsV25Vb0E=