{
 "title": "PDF RAG CHATBOT MONITORING PANEL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cost ( tokens +energy ) - total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "avg(pdf_rag_cost_per_query)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Energy consumption - total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(pdf_rag_energy_kwh_per_query)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon emissions  (CO2) - total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(pdf_rag_carbon_mg_per_query)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per interaction - average ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(pdf_rag_latency_per_query)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Answer score (by llm evaluator)  - average ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "/ 1.0" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(pdf_rag_llm_evaluator)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User satisfaction per dollar ( Histogram )",
   "type": "histogram",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pdf_rag_satisfaction_per_dollar",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Satisfaction per dollar  - average ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/ 1.0" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(pdf_rag_satisfaction_per_dollar)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pdf_rag_latency_per_query", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User satisfaction  - average ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/ 5.0" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(pdf_rag_user_satisfaction)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Context adherence per dollar  - average ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "/ 1.0" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(pdf_rag_quality_per_dollar)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context adherence per dollar ( Histogram )",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 9, "x": 7, "y": 20 },
   "targets": [
    { "expr": "pdf_rag_quality_per_dollar", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tokens usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    { "expr": "sum(pdf_rag_tokens_per_query)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Context adherence  - average ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "/ 1.0" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(pdf_rag_context_adherence_per_query)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Answer score (by llm evaluator, Histogram)",
   "type": "histogram",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 32 },
   "targets": [
    { "expr": "pdf_rag_llm_evaluator", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User satisfaction ( Histogram )",
   "type": "histogram",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 32 },
   "targets": [
    { "expr": "pdf_rag_user_satisfaction", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Energy consumption ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "pdf_rag_energy_kwh_per_query", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Context Adherence per interaction (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "pdf_rag_context_adherence_per_query",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost per interaction ( tokens +energy, Histogram)",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "pdf_rag_cost_per_query", "legendFormat": "__auto" }
   ]
  }
 ]
}